### PR TITLE
Make kairos-agent support install local bundle

### LINKED ISSUE #1295: kairos-agent support install local bundle
**Is your feature request related to a problem? Please describe.**

when install OS, it support install local bundle, but `kairos-agent install-bundle` not.
**Describe the solution you'd like**

`kairos-agent install --local-file=true`
**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by scuzhanglei**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1295

### CODE REVIEW

**Comment by mudler** [comment]
Looks good here! thanks @scuzhanglei !

I'd say you also want to add yourself in https://github.com/kairos-io/kairos/blob/master/CONTRIBUTORS.md =)

**Review by mudler — APPROVED** [review]

**Review by mauromorales — APPROVED** [review]
nice!

**Comment by mudler** [comment]
Thanks @scuzhanglei ! Please, feel free to create a new PR to add yourself to our CONTRIBUTORS file, or we will do that later =)

**Comment by jimmykarily** [comment]
@scuzhanglei : https://github.com/kairos-io/kairos/pull/1339/files

Feel free to add a comment with the name to use instead of your handle if you prefer that.

**Pull request merged**
