### PR TITLE
v2.0.3 branch: immucore v.0.0.18 + fix for config merge

### PR DESCRIPTION
**Pull request by Itxaka**
Brings:

 - immucore v0.0.18+lvm packages for rockylinux+fedora
 - https://github.com/kairos-io/kairos/pull/1343
 - Fixes the release test (CI only)
 - Download only the x86 iso for testing (CI only)

### CODE REVIEW

**Comment by Itxaka** [comment]
Backport seems good, everything green (missing the fix for the upgraded test)

**Comment by Itxaka** [comment]
also backported 1261d4b73e4885d776bbf2683aa714e179f09a74 so we dont have any breaking tests in this branch anymore :D

**Comment by Itxaka** [comment]
Last piece backported, once its green we can merge + tag

**Review by mauromorales — APPROVED** [review]
lgtm

**Pull request merged**
