### PR TITLE
🔧 Add earthlyignore file

### LINKED ISSUE #693: Add and maintain .earthlyignore file
**Is your feature request related to a problem? Please describe.**

We need to add `.earthlyfile` to enhance build speed locally. Without this we are sending a lot of unneeded
files to buildkit, especially true for large ISOs under `build/`.

**Describe the solution you'd like**
For a start an earthlyingore with:
```
build/*iso
```

**Describe alternatives you've considered**

Manually clean the build directory every time I build an new ISO.

**Additional context**

https://docs.earthly.dev/docs/earthfile/earthlyignore

### PR DESCRIPTION
**Pull request by oz123**
**What this PR does / why we need it**:
We need to add .earthlyfile to enhance build speed locally. Without this we are sending a lot of unneeded
files to buildkit, especially true for large ISOs under build/.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #693

### CODE REVIEW

**Review by paynejacob — DISMISSED** [review]

**Review by Itxaka — COMMENTED** [review]
I would just add the whole build dir instead of only the is, as you may have img files or xz files on it

**Comment by mudler** [comment]
upgrade tests seems to use `build` https://github.com/kairos-io/kairos/actions/runs/4057373981/jobs/6983975639

**Comment by Itxaka** [comment]
> upgrade tests seems to use `build` [kairos-io/kairos/actions/runs/4057373981/jobs/6983975639](https://github.com/kairos-io/kairos/actions/runs/4057373981/jobs/6983975639)

weird, that downloads the required iso into the root dir. I would instead change the job to move the ISO into the test dir or a special dir instead of removing the earthly file on those tests...

**Comment by oz123** [comment]
TBH, I think you are correct. It's the right thing to do, but I don't want to mess further with the Earthlyfile.
Every commit push cycle is really slow, and we can do this in a separate PR to make all the tests use the same directory.
Right now, I just want all the team to use the earthlyignore in the most basic version.
Once this is the master, everyone uses it, so we can incrementally improve it.

**Review by mudler — APPROVED** [review]

**Pull request merged**
