### PR TITLE
:robot: run install test under earthly

### PR DESCRIPTION
**Pull request by Itxaka**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by Itxaka** [comment]
I see now what @jimmykarily meant, this is slow as heck.

**Comment by jimmykarily** [comment]
But running it outside earthly doesn't make it automatically faster. We need to enable KVM the here are lost of hoops to jump through to achieve that.

**Comment by Itxaka** [comment]
> But running it outside earthly doesn't make it automatically faster. We need to enable KVM the here are lost of hoops to jump through to achieve that.

kind of does lol. Im guessing the extra layer of dockering

**Comment by jimmykarily** [comment]
I managed to get tests to run with KVM here: https://github.com/kairos-io/provider-kairos/pull/306 (self-hosted runners). When that gets merged we can plan how to do that for this repo too. We may need more resources for that.

**Pull request closed without merging**
