### PR TITLE
:bug: Schema for groups is not working

### PR DESCRIPTION
**Pull request by Itxaka**
Looks like the schema for the user thinks groups is a string, while checking the code it seems to be more a list of strings and that matches with the yip library and how it parses the groups.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kairos-io/kairos/issues/1083

### CODE REVIEW

**Review by mudler — APPROVED** [review]
Looks good and good catch,  thanks @Itxaka !

**Comment by mudler** [comment]
whats with tumbleweed nowwwww

**Review by mauromorales — APPROVED** [review]
oopsie, thanks for spotting it!

**Comment by Itxaka** [comment]
All credit to nan0man on slack for finding it out!

**Comment by Itxaka** [comment]
Fixes: https://github.com/kairos-io/kairos/issues/1083

**Comment by Itxaka** [comment]
Dont think it needs to wait for the full CI

**Pull request merged**
