### PR TITLE
ci: build darwin binary (macOS cli)

### PR DESCRIPTION
**Pull request by renanqts**
We would get rid of #36

### CODE REVIEW

**Comment by mudler** [comment]
Thanks! although this seems to not work as-is, looks like the screenshot part does not work on darwin:

```
#   ⨯ build failed after 37.70s error=failed to build for darwin_amd64_v1: exit status 2: # github.com/kbinani/screenshot
../go/pkg/mod/github.com/kbinani/screenshot@v0.0.0-20210720154843-7d3a670d8329/screenshot.go:11:10: undefined: GetDisplayBounds
../go/pkg/mod/github.com/kbinani/screenshot@v0.0.0-20210720154843-7d3a670d8329/screenshot.go:17:9: undefined: Capture
``` 

would make sense to disable screenshot capturing on darwin if there isn't any other library providing the same capabilities for macOS - but as I don't own one, can't even double check if it actually works.

been testing with: 
```
 goreleaser build --rm-dist --skip-validate --snapshot
```

**Comment by renanqts** [comment]
@mudler 

I also faced with another one

```
../../go/pkg/mod/github.com/kbinani/screenshot@v0.0.0-20210720154843-7d3a670d8329/screenshot.go:11:10: undefined: GetDisplayBounds
../../go/pkg/mod/github.com/kbinani/screenshot@v0.0.0-20210720154843-7d3a670d8329/screenshot.go:17:9: undefined: Capture
# github.com/elastic/gosigar
../../go/pkg/mod/github.com/elastic/gosigar@v0.14.2/concrete_sigar.go:20:12: cpuUsage.Get undefined (type Cpu has no field or method Get)
../../go/pkg/mod/github.com/elastic/gosigar@v0.14.2/concrete_sigar.go:30:14: cpuUsage.Get undefined (type Cpu has no field or method Get)
../../go/pkg/mod/github.com/elastic/gosigar@v0.14.2/concrete_sigar.go:49:11: l.Get undefined (type LoadAverage has no field or method Get)
../../go/pkg/mod/github.com/elastic/gosigar@v0.14.2/concrete_sigar.go:55:11: m.Get undefined (type Mem has no field or method Get)
../../go/pkg/mod/github.com/elastic/gosigar@v0.14.2/concrete_sigar.go:61:11: s.Get undefined (type Swap has no field or method Get)
../../go/pkg/mod/github.com/elastic/gosigar@v0.14.2/concrete_sigar.go:67:11: p.Get undefined (type HugeTLBPages has no field or method Get)
../../go/pkg/mod/github.com/elastic/gosigar@v0.14.2/concrete_sigar.go:79:12: fd.Get undefined (type FDUsage has no field or method Get)
../../go/pkg/mod/github.com/elastic/gosigar@v0.14.2/sigar_darwin.go:13:12: undefined: sysctlbyname
```

**Comment by renanqts** [comment]
I'm not sure it makes sense to compile some deps in Darwin. 
I saw this PR https://github.com/c3os-io/c3os/pull/37 where you mentioned that you are decapling it. Should we wait for it? My expectation is that we don't have those deps in the `cli` itself.

**Comment by mudler** [comment]
> I'm not sure it makes sense to compile some deps in Darwin. I saw this PR #37 where you mentioned that you are decapling it. Should we wait for it? My expectation is that we don't have those deps in the `cli` itself.

Thank you so much for the pr!

yup makes sense, although some of the issues would persist, like the one I've mentioned, but gosigar should be fine. Let's pick it up from there

**Comment by mudler** [comment]
@renanqts thanks again for the efforts, the CLI has moved to kairos-io/provider-kairos, however the problem still persist (that the screenshot lib isn't available) so I'm closing this PR as it is now obsoleted.  What we could do is disable the screenshot feature on macOS, and just take an image file, feel free to open an issue so we can track it

**Pull request closed without merging**
