### PR TITLE
:bug: Add missing lvm packages in fedora/rockylinux + bump immucore to v0.0.18

### PR DESCRIPTION
**Pull request by Itxaka**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by mauromorales — APPROVED** [review]
lgtm

**Comment by Itxaka** [comment]
This would fix https://github.com/kairos-io/kairos/issues/1342

**Comment by Itxaka** [comment]
Also needs https://github.com/kairos-io/kairos/pull/1343 backported, waiting until its merged

**Comment by Itxaka** [comment]
crap, this was set against the wrong branch!

**Pull request closed without merging**
