### PR TITLE
Run encryption tests in KVM nodes

### LINKED ISSUE #2715: Alpine local encryption test is breaking
```
mkdir -p ~/.earthly/
  cat << EOF > ~/.earthly/config.yml
  global:
    buildkit_additional_config: |
      [registry."docker.io"]
        mirrors = ["registry.docker-mirror.svc.cluster.local:[5](https://github.com/kairos-io/kairos/actions/runs/9882563465/job/27295942578?pr=2714#step:9:5)000"]
      [registry."registry.docker-mirror.svc.cluster.local:5000"]
        insecure = true
        http = true
  EOF
  earthly -P +run-qemu-datasource-tests --PREBUILT_ISO=$(ls *ubuntu*.iso) --TEST_SUITE=reset-test --FLAVOR=ubuntu
```

results in 

```
**  +run-qemu-datasource-tests *failed* | • [FAILED] [1226.087 seconds]
  +run-qemu-datasource-tests *failed* | kairos reset test [BeforeEach] auto installs, reboots and passes functional tests resets [reset-test]
  +run-qemu-datasource-tests *failed* |   [BeforeEach] /test/tests/reset_test.go:14
  +run-qemu-datasource-tests *failed* |   [It] /test/tests/reset_test.go:33
  
  +run-qemu-datasource-tests *failed* |   [FAILED] Timed out after 1225.051s.
  +run-qemu-datasource-tests *failed* |   Expected
  +run-qemu-datasource-tests *failed* |       <string>: 
  +run-qemu-datasource-tests *failed* |   to equal
  +run-qemu-datasource-tests *failed* |       <string>: ping\n
  +run-qemu-datasource-tests *failed* |   In [BeforeEach] at: /go/pkg/mod/github.com/spectrocloud/peg@v0.0.0-20240405075800-c5da7125e30f/matcher/helpers.go:264 @ 07/11/24 00:19:25.982
  +run-qemu-datasource-tests *failed* | ------------------------------
  +run-qemu-datasource-tests *failed* | SSSSSSS
  
  +run-qemu-datasource-tests *failed* | Summarizing 1 Failure:
  +run-qemu-datasource-tests *failed* |   [FAIL] kairos reset test [BeforeEach] auto installs, reboots and passes functional tests resets [reset-test]
  +run-qemu-datasource-tests *failed* |   /go/pkg/mod/github.com/spectrocloud/peg@v0.0.0-20240405075800-c5da7125e30f/matcher/helpers.go:264
  
  +run-qemu-datasource-tests *failed* | Ran 1 of 21 Specs in 1226.088 seconds
  +run-qemu-datasource-tests *failed* | FAIL! -- 0 Passed | 1 Failed | 0 Pending | 20 Skipped
  +run-qemu-datasource-tests *failed* | --- FAIL: TestSuite (1226.09s)**
```

e.g. https://github.com/kairos-io/kairos/actions/runs/9882563465/job/27295942578?pr=2714

Also we don't run this test on master, so you need to open a PR to see it fail atm

### PR DESCRIPTION
**Pull request by Itxaka**
**What this PR does / why we need it**:

Looks like the VM is running out of resources when running, so move the tests to our KVM workers and limit the cpu/memory for the VM

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2715

### CODE REVIEW

**Comment by Itxaka** [comment]
This makes it pass the encryption alpine tests with no issues.

**Comment by Itxaka** [comment]
Moving them back to github hosted runnners to see if it was a problem with the default mem/cpu values?

**Comment by Itxaka** [comment]
yep, seems to confirm that the problem was that there was not a set limit in the VM, so it may have run out of resources while running the test.

**Review by mauromorales — APPROVED** [review]
nice catch

**Pull request merged**
