### PR TITLE
:bug: Ensure data source is ready during reset

### LINKED ISSUE #1178: :bug: Reset does not work on physical hardware (INTEL NUC as Example)
**Kairos version:**
1.5,1.6,2.0

**CPU architecture, OS, and Version:**
x86 12 Generation Intel.  OS version does not matter.  The result is the same.

**Describe the bug**
When sending a node to reset, the node never comes back online.  It simply sits at a blank screen.  The node boots into recovery, but the reset command is never applied.

**To Reproduce**
Load an Intel NUC and send it to reset.

**Expected behavior**
The Node should reset back to the original state.

### PR DESCRIPTION
**Pull request by mudler**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1178

### CODE REVIEW

**Review by mauromorales — APPROVED** [review]
lgtm

**Review by Itxaka — APPROVED** [review]
does this make sense? I mean, 5 minutes waiting for source+60 seconds for reset is quite a lot...we need to fix the datasource wait!

**Comment by mudler** [comment]
> does this make sense? I mean, 5 minutes waiting for source+60 seconds for reset is quite a lot...we need to fix the datasource wait!

yep agreed, data source pulling code is rather suboptimal :/

**Comment by mudler** [comment]
Ok all green, merging!

**Pull request merged**
