### PR TITLE
Consume reusable linting workflow

### PR DESCRIPTION
**Pull request by jimmykarily**
part of: https://github.com/kairos-io/kairos/issues/1234

### CODE REVIEW

**Comment by jimmykarily** [comment]
The hadolint errors were there before but the earthly target has a mistake and didn't catch them. There are legitimate issues we should fix.

**Comment by jimmykarily** [comment]
I'm not sure I agree with the hadolint suggestions:

```
./images/Dockerfile.opensuse-leap-arm-rpi:9 DL3037 warning: Specify version with `zypper install -y <package>=<version>`.
```
from [here](https://github.com/kairos-io/kairos/actions/runs/4873588267/jobs/8693376161?pr=1371). As far as I know, not every version is available for installation at any given image. It's the responsibility of the distribution to include package versions that "work". I understand builds should be reproducible but I'm not sure pinning the version of every package is doable.

**Comment by jimmykarily** [comment]
I created a `.hadolint.yaml` file to assign them the severity "info" and then ignore them (not fail on them).

**Review by mauromorales — APPROVED** [review]
lgtm

**Pull request merged**
