### PR TITLE
Deeply merge yamls in original data

### PR DESCRIPTION
**Pull request by jimmykarily**
This is part of https://github.com/kairos-io/kairos/issues/399

I need this merged first, so I can use it on the `kcrypt` side. Then I will bump kcrypt here to use the new config pkg.

### CODE REVIEW

**Review by mauromorales — APPROVED** [review]
would it make sense to use something like [mergo](https://github.com/imdario/mergo) instead? 

LGTM

**Review by Itxaka — DISMISSED** [review]
Pretty straightforward, looking good

**Comment by jimmykarily** [comment]
> would it make sense to use something like [mergo](https://github.com/imdario/mergo) instead?
> 
> LGTM

My research didn't reveal this library, nice! Seems to work. Updating the PR.

**Review by Itxaka — APPROVED** [review]
IMHO a link for merging 2 yamls is too much. Nothing wrong with having 30 lunes to do that on our own code. Still lgtm

**Comment by jimmykarily** [comment]
> IMHO a lib for merging 2 yamls is too much. Nothing wrong with having 30 lines to do that on our own code. Still lgtm

I wasn't too confident about the function to be honest (e.g. future "merged" I haven't though of). The lib is being used by many projects, I expect it to be more mature.

**Review by mauromorales — APPROVED** [review]
lgtm

**Comment by mudler** [comment]
It seems to break something: https://github.com/kairos-io/kairos/actions/runs/3946782970/jobs/6755339985

**Comment by jimmykarily** [comment]
> It seems to break something: https://github.com/kairos-io/kairos/actions/runs/3946782970/jobs/6755339985

I saw this after merge (I ignored most failures because they were network timeouts). I'm investigating now. I used the test's conf file to install kairos and the expected path exists. Trying to run the test locally now.

**Comment by jimmykarily** [comment]
Test passes, locally. Re-triggered on CI: https://github.com/kairos-io/kairos/actions/runs/3946782970/jobs/6757307211

**Comment by jimmykarily** [comment]
I did a manual test. It has something to do with the change here: https://github.com/kairos-io/kairos/pull/651 (because of this: https://github.com/kairos-io/kairos/blob/6168edaf2d3b97c12ad6f3755ac65a13fc362dfc/examples/bundle/Dockerfile#L11). 
Relevant debugging:

```
kairos-21vm:/home/kairos # systemd-sysext refresh
No suitable extensions found (1 ignored due to incompatible version).
kairos-21vm:/home/kairos # systemd-sysext refresh --force
Using extensions 'kubo'.
Merged extensions into '/usr'.
kairos-21vm:/home/kairos # systemd-sysext 
HIERARCHY EXTENSIONS SINCE                      
/opt      none       -                          
/usr      kubo       Wed 2023-01-18 14:10:02 UTC
...
cat /usr/local/lib/extensions/kubo/usr/lib/extension-release.d/extension-release.kubo
ID=kairos
VERSION_ID=v1.4.0-28-gfc2585b-dirty
kairos-21vm:/home/kairos # cat /etc/os-release 
NAME="kairos-core-opensuse"
VERSION="v1.4.0-25-g79c4a94"
```

**Pull request merged**
