### PR TITLE
:robot: Bump osbuilder and drop keys

### PR DESCRIPTION
**Pull request by Itxaka**
Bumps osbuilder to latest, drops test keys and makes the earthly target create them on the fly when building the image as we only need them to sign the images and we dont plan to do anything else with them, we can simply fully drop them and generate them on demand for ci

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by Itxaka** [comment]
ahhh unless we set the loader.conf entry to be `secure-boot-enroll if-safe` which would autoenroll only in VMs, our uki tests are broken as we cannot select the entry programatically...

**Comment by mauromorales** [comment]
ah this answers my question on the other PR hehehe

**Review by mauromorales — APPROVED** [review]
niceee

**Comment by jimmykarily** [comment]
I hope git is clever enough to handle this but make sure that they are still removed after rebasing to this: https://github.com/kairos-io/kairos/pull/2331/files

**Pull request merged**
