### PR TITLE
:robot: Run framework build on self-hosted

### PR DESCRIPTION
**Pull request by mudler**
**What this PR does / why we need it**:
Those jobs are small (typically runs for 4/5mins) and might be useful to re-use the cache in such case which makes it faster. This is a test - It is also better probably to free some slots, as no other jobs depends on the fw images.

### CODE REVIEW

**Review by mauromorales — DISMISSED** [review]
lgtm

**Review by oz123 — DISMISSED** [review]

**Review by jimmykarily — APPROVED** [review]

**Comment by jimmykarily** [comment]
'setup-docker' is doing something wrong:

```
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor | sudo cat >/usr/share/keyrings/docker-archive-keyring.gpg
```
the last command `sudo cat` is not correct. This is not the right way to redirect output with sudo persmissions.

Similarly, this fails in our runners:

```
runner@kairos-runners-f6cw7-cmzng:/$ sudo echo "test" > /usr/share/keyrings/test
bash: /usr/share/keyrings/test: Permission denied
```

but this works:

```
 sudo /bin/sh -c 'echo "test" > /usr/share/keyrings/test'
```

**Comment by jimmykarily** [comment]
This works:

```
runner@kairos-runners-f6cw7-cmzng:/$ echo "test" | sudo tee /usr/share/keyrings/test
test
```

but this doesn't:

```
runner@kairos-runners-f6cw7-cmzng:/$ echo "test" | sudo cat >/usr/share/keyrings/test
bash: /usr/share/keyrings/test: Permission denied
```

other than the fact that `tee` also prints the text, it seems to be the simplest fix. We could try to upstream it. Unless someone has a better idea, I don't speak good bash.

**Comment by mudler** [comment]
all good now :)

**Pull request merged**
