### PR TITLE
:bug: Fix version list

### LINKED ISSUE #1320: :bug: `kairos-agent upgrade` is wrong
**Kairos version:**
```
kairos-LVM:~ # cat /etc/os-release 
NAME="kairos-core-opensuse-leap"
VERSION="v2.0.0-28-g434edb5-dirty"
ID="kairos"
ID_LIKE="kairos-core-opensuse-leap"
VERSION_ID="v2.0.0-28-g434edb5-dirty"
PRETTY_NAME="kairos-core-opensuse-leap v2.0.0-28-g434edb5-dirty"
ANSI_COLOR="0;32"
BUG_REPORT_URL="https://github.com/kairos-io/kairos/issues"
HOME_URL="https://github.com/kairos-io/kairos"
IMAGE_REPO="quay.io/kairos/core-opensuse-leap"
IMAGE_LABEL="latest"
GITHUB_REPO="kairos-io/kairos"
VARIANT="core"
```

**CPU architecture, OS, and Version:**
```
Linux kairos-LVM 5.14.21-150500.48-default #1 SMP PREEMPT_DYNAMIC Thu Apr 6 08:23:23 UTC 2023 (50e397b) x86_64 x86_64 x86_64 GNU/Linux
```

**Describe the bug**
running `kairos-agent upgrade` results in the agent suggesting to use version v1.0.0 as latest.

**To Reproduce**
```
kairos-LVM:~ # kairos-agent upgrade
Latest release is v1.0.0
Are you sure you want to upgrade to this release? (y/n) n
```

**Expected behavior**
running `kairos-agent upgrade` suggest the real latest version (i.e. v2.0.0 in this particular case?

**Logs**

**Additional context**

### PR DESCRIPTION
**Pull request by Itxaka**
First version in the list is the latest one.
Alos moves the check for same version above the current place, so it can check before asking if you want to update to the same version

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1320

### CODE REVIEW

**Review by mauromorales — APPROVED** [review]
this is one of those things were I think having unit tests would be useful

lgtm

**Comment by Itxaka** [comment]
> this is one of those things were I think having unit tests would be useful
> 
> lgtm

good point, will add at least 1 if Im able to override the os-release fo the test somehow :D

**Comment by Itxaka** [comment]
Will also expand this to manage a list of server versions, which can be sorted properly

**Comment by mudler** [comment]
maybe we can even use https://github.com/charmbracelet/bubbletea ? :pleading_face:

**Comment by Itxaka** [comment]
> maybe we can even use [charmbracelet/bubbletea](https://github.com/charmbracelet/bubbletea) ? pleading_face

image

**Comment by Itxaka** [comment]
Updated the version stuff to use a proper parser for semver versions so we can be sure to alwasy select the highest one.

Alos opens the door to more fancy stuff, like offering pre-release versions and decently comparing versions. Also adds a test as a side effect :P

**Review by mauromorales — DISMISSED** [review]
lgtm

**Review by mauromorales — APPROVED** [review]

**Pull request merged**
