### PR TITLE
Add systemd boot standard image to the build matrix

### PR DESCRIPTION
**Pull request by jimmykarily**
to make it easier to build UKI artifacts from it

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by jimmykarily** [comment]
This would also build an `.iso` file. What would happen if one booted it as-is, without passing it through enki first?

**Comment by jimmykarily** [comment]
Hm, to begin with, an iso can't be built:

```bash
earthly -P +iso --FAMILY=ubuntu --FLAVOR=ubuntu --FLAVOR_RELEASE=24.04 --VARIANT=standard --MODEL=generic --BASE_IMAGE=ubuntu:24.04 --BOOTLOADER=systemd-boot --K3S_VERSION=1.31.1

...

                +iso *failed* | 2024-10-09T13:59:34Z DBG Running cmd: 'rsync --progress --partial --human-readable --archive --xattrs --acls --exclude=/mnt --exclude=/proc --exclude=/sys --exclude=/dev --exclude=/tmp --exclude=/host --exclude=/run /build/image/ /tmp/enki-iso183628896/rootfs/'
                +iso *failed* | 2024-10-09T13:59:37Z INF Finished syncing
                +iso *failed* | 2024-10-09T13:59:37Z INF Finished copying /build/image into /tmp/enki-iso183628896/rootfs
                +iso *failed* | 2024-10-09T13:59:37Z INF Preparing ISO image root tree...
                +iso *failed* | 2024-10-09T13:59:37Z INF Copying /grub2 source to /tmp/enki-iso183628896/iso
                +iso *failed* | 2024-10-09T13:59:37Z INF Starting rsync...
                +iso *failed* | 2024-10-09T13:59:37Z DBG Running cmd: 'rsync --progress --partial --human-readable --archive --xattrs --acls --exclude=/mnt --exclude=/proc --exclude=/sys --exclude=/dev --exclude=/tmp --exclude=/host --exclude=/run /grub2/ /tmp/enki-iso183628896/iso/'
                +iso *failed* | 2024-10-09T13:59:37Z INF Finished syncing
                +iso *failed* | 2024-10-09T13:59:37Z INF Finished copying /grub2 into /tmp/enki-iso183628896/iso
                +iso *failed* | 2024-10-09T13:59:37Z ERR No initrd file found
                +iso *failed* | 2024-10-09T13:59:37Z ERR Could not find kernel and/or initrd
                +iso *failed* | 2024-10-09T13:59:37Z ERR Failed preparing ISO's root tree: No file found with prefixes: [initrd initramfs]
                +iso *failed* | 2024-10-09T13:59:37Z ERR 1 error occurred:
                +iso *failed* | 	* No file found with prefixes: [initrd initramfs]

                +iso *failed* |
                +iso *failed* | ERROR Earthfile:576:4
                +iso *failed* |       The command
                +iso *failed* |           RUN /entrypoint.sh --name $ISO_NAME --debug build-iso --squash-no-compression --date=false dir:/build/image --output /build/
                +iso *failed* |       did not complete successfully. Exit code 1

Help: To debug your build, you can use the --interactive (-i) flag to drop into a shell of the failing RUN step: "earthly -i -P +iso --FAMILY=ubuntu --FLAVOR=ubuntu --FLAVOR_RELEASE=24.04 --VARIANT=standard --MODEL=generic --BASE_IMAGE=ubuntu:24.04 --BOOTLOADER=systemd-boot --K3S_VERSION=1.31.1"
```

**Comment by jimmykarily** [comment]
The earthly target tries to build an iso with `enki build-iso` (through the `earthly +iso` target) and this doesn't work because [it expects to find a `/boot/initrd`](https://github.com/kairos-io/kairos-agent/blob/a3aadbbaa970c55cbcf93d9fc2bf49d51a6a2fe3/pkg/elemental/elemental.go#L587) file and that doesn't happen because we [don't have dracut around](https://github.com/kairos-io/kairos/blob/473bc838fb0453975bf59186b2e36fc4c7479105/images/Dockerfile.kairos-ubuntu#L470-L475) so we don't create the symlink. This PR was about creating a container image only. The iso is created with `enki build-uki` command.
The pipeline can't be re-used so it requires more work to get this to work. I will close this until there is a user request to have it.

**Comment by jimmykarily** [comment]
Do we intentionally point to non existent files here? https://github.com/kairos-io/kairos/pull/2929/files#diff-e426ed45842837026e10e66af23d9c7077e89eacbe6958ce7cb991130ad05adaR373

(https://github.com/kairos-io/kairos/actions/runs/11211362726/job/31166937967#step:16:12)

We don't release uki isos at the moment. If we want to fix it, I think we will need to name the isos differently with enki because the "core" and "standard" one would get the same name I think.

**Review by mauromorales — COMMENTED** [review]
lgtm but we'll only test with a release so I'd suggest some alpha

**Comment by Itxaka** [comment]
> Do we intentionally point to non existent files here? https://github.com/kairos-io/kairos/pull/2929/files#diff-e426ed45842837026e10e66af23d9c7077e89eacbe6958ce7cb991130ad05adaR373
> 
> (https://github.com/kairos-io/kairos/actions/runs/11211362726/job/31166937967#step:16:12)
> 
> We don't release uki isos at the moment. If we want to fix it, I think we will need to name the isos differently with enki because the "core" and "standard" one would get the same name I think.

I think that's a leftover as we cannot release isos or EFI files as they are not signed or would be signed with our test keys.

Artifacts being pushed is ok as you can generate your own isos or upgrade artifacts with them, but isos and EFI files are a big no no

**Comment by bencorrado** [comment]
> > Do we intentionally point to non existent files here? https://github.com/kairos-io/kairos/pull/2929/files#diff-e426ed45842837026e10e66af23d9c7077e89eacbe6958ce7cb991130ad05adaR373
> > 
> > (https://github.com/kairos-io/kairos/actions/runs/11211362726/job/31166937967#step:16:12)
> > 
> > We don't release uki isos at the moment. If we want to fix it, I think we will need to name the isos differently with enki because the "core" and "standard" one would get the same name I think.
> 
> I think that's a leftover as we cannot release isos or EFI files as they are not signed or would be signed with our test keys.
> 
> Artifacts being pushed is ok as you can generate your own isos or upgrade artifacts with them, but isos and EFI files are a big no no

I think the realistic option to build iso files is to use shim similar to what mkosi did https://github.com/systemd/mkosi/issues/1863

This would allow for quicker testing for people who want to try out Kairos.

**Comment by Itxaka** [comment]
> > > Do we intentionally point to non existent files here? https://github.com/kairos-io/kairos/pull/2929/files#diff-e426ed45842837026e10e66af23d9c7077e89eacbe6958ce7cb991130ad05adaR373
> > > 
> > > (https://github.com/kairos-io/kairos/actions/runs/11211362726/job/31166937967#step:16:12)
> > > 
> > > We don't release uki isos at the moment. If we want to fix it, I think we will need to name the isos differently with enki because the "core" and "standard" one would get the same name I think.
> > 
> > I think that's a leftover as we cannot release isos or EFI files as they are not signed or would be signed with our test keys.
> > 
> > Artifacts being pushed is ok as you can generate your own isos or upgrade artifacts with them, but isos and EFI files are a big no no
> 
> I think the realistic option to build iso files is to use shim similar to what mkosi did https://github.com/systemd/mkosi/issues/1863
> 
> This would allow for quicker testing for people who want to try out Kairos. 

This is just for uki where you sign the full EFI files. In that case the shim does not help at all. For non-uki isos under UEFI we already use the upstream shim so it should work under secureboot without issues and without needing to sign anything.

**Review by mauromorales — APPROVED** [review]

**Pull request merged**
