### PR TITLE
🐛 Remove openntpd

### LINKED ISSUE #519: Alpine: use busybox ntpd
**Kairos version:** alpine-ubuntu and probably alpine-opensuse-leap

**CPU architecture, OS, and Version:** amd64

**Describe the bug**
It could be just a problem for my server, but when openntpd is used, prometheus gives an alert:

```
 Clock on <hostname>:9796 is out of sync by more than 300s. Ensure NTP is configured correctly on this host.
```
I stopped the openntpd-service, patched `/etc/init.d/ntpd` to use the busybox binary (necessary since ntpd doesn't point to busybox), started the ntpd-service and the alert disappears.

(There would be no need for a patch if openntpd wasn't installed in the alpine flavor, ntpd would point to busybox)

**To Reproduce**
Join an alpine k3s-agent (no special config) to a cluster with prometheus monitoring and alerting installed. After a short period the alert is firing.

**Expected behavior**
No such errors.

**Question**
Is it mandatory to install a dedicated ntpd-package on alpine? Why not stick with the (working) busybox-version?

It could also help reduce confusion. See #476

### PR DESCRIPTION
**Pull request by christianprim**
Signed-off-by: Christian Prim <christian.prim@gmx.ch>

**What this PR does / why we need it**:
Removes openntpd from Alpine images as it makes some trouble

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #519

### CODE REVIEW

**Comment by christianprim** [comment]
@mudler : where can I find the iso-image from this run so I can test if busybox ntpd really gets started?

**Comment by mudler** [comment]
hey @christianprim thx for taking a stab at it! The ISOs are available in the action summary page after the build ends: https://github.com/kairos-io/kairos/actions/runs/3741359725

**Review by mudler — APPROVED** [review]
Looks good here, @christianprim if you are giving it a try I'll wait for your feedback - we can also add a e2e test in the acceptance suite I think  cc @jimmykarily

**Comment by christianprim** [comment]
My laptop is an older one, so the install lasted longer under qemu... But I can report, that ntpd has started!

**Comment by jimmykarily** [comment]
> My laptop is an older one, so the install lasted longer under qemu... But I can report, that ntpd has started!

I've found out that `--enable-kvm` makes a big difference in performance (in case you didn't know that).

**Review by jimmykarily — APPROVED** [review]

**Comment by jimmykarily** [comment]
It's green, merged. Thanks @christianprim !

**Pull request merged**
