### PR TITLE
add support for RPI3 for alpine flavor

### PR DESCRIPTION
**Pull request by Ludea**
**What this PR does / why we need it**:
Add support for RP3

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #
With 2.4 release, RPI3 and RPI4 get separate img

### CODE REVIEW

**Comment by Itxaka** [comment]
Looks good. We may need to change some things before getting this merged to separate the rpi images and artifacts into 2 different repos maybe as not sure if the artifacts have the proper naming to be alongside...

**Comment by Ludea** [comment]
`+base-image | linux/arm64 | FLAVOR=opensuse-leap-arm-rpi MODEL=rpi4 VARIANT=core` => https://github.com/kairos-io/kairos/actions/runs/6185486007/job/16791177481#step:14:2663
seems model var is not updated for base-image

**Comment by Ludea** [comment]
there is also 
`              common | System has not been booted with systemd as init system (PID 1). Can't operate.
              common | Failed to connect to bus: Host is down
              common | done]`

**Comment by Itxaka** [comment]
> there is also ` common | System has not been booted with systemd as init system (PID 1). Can't operate. common | Failed to connect to bus: Host is down common | done]`

default build for prs is rpi4 and just one flavor :)
This would be reflected on master jobs which run the full flavor suite: https://github.com/kairos-io/kairos/blob/master/.github/workflows/image-arm.yaml#L25

**Comment by Ludea** [comment]
> Looks good. We may need to change some things before getting this merged to separate the rpi images and artifacts into 2 different repos maybe as not sure if the artifacts have the proper naming to be alongside...

https://github.com/kairos-io/kairos/actions/runs/6185486007/job/16791177481#step:14:32128
it's tagged with rpi4

**Comment by Itxaka** [comment]
> > Looks good. We may need to change some things before getting this merged to separate the rpi images and artifacts into 2 different repos maybe as not sure if the artifacts have the proper naming to be alongside...
> 
> [kairos-io/kairos/actions/runs/6185486007/job/16791177481#step:14:32128](https://github.com/kairos-io/kairos/actions/runs/6185486007/job/16791177481#step:14:32128) it's tagged with rpi4

yes, on PRs we only build that: https://github.com/kairos-io/kairos/blob/master/.github/workflows/image-arm-pr.yaml#L19

**Comment by Itxaka** [comment]
tested this locally and it builds the image as expected buuuuut.... we dont set the output repo properly:

`quay.io/kairos/core-alpine-arm-rpi:v2.4.0-5-gd252ef2`

This means that if we build alpine-arm-rpi for both rpi3 and rpi4 they will get mixed and with no way of knowing which image is what...

**Comment by Itxaka** [comment]
This will probably need to wait for https://github.com/kairos-io/kairos/issues/1694 as we are renaming the repos, so we may do the distinction there somehow

**Pull request closed without merging**
