### PR TITLE
:bug: Fix configuration not being merge

### LINKED ISSUE #687: 🐛 Manual install doesnt pick options from config file
**Kairos version:**
master

**CPU architecture, OS, and Version:**
all

**Describe the bug**
When using a config file and doing manual install `kairos-agent manual-install CONFIG` supposedly there is an `options` key in the config that should be passed down to the installer.
Unfortunately this does not work as it uses a different path, so it loads the file and dumps it into `option["cc"]` and there is nothing to merge those options into the config properly.

An example of how its merged during a normal install is in https://github.com/kairos-io/kairos/blob/master/internal/agent/install.go#L85

**To Reproduce**
create config file with options, call `kairos-agent manual-install CONFIG`

**Expected behavior**

Options are respected and passed down

**Logs**

**Additional context**

### PR DESCRIPTION
**Pull request by oz123**
Fix #687.

### CODE REVIEW

**Comment by oz123** [comment]
@jimmykarily I'm having troubles understanding why upgrade with opensuse works, but fails with alpine. Is this random?

**Review by Itxaka — COMMENTED** [review]
codewise looks good to me, but it seems like we are changing the outcome somehow...I also dont get it :(

**Comment by oz123** [comment]
The tests run perfectly well locally with:
```
earthly +all --IMAGE=quay.io/kairos/core-alpine-opensuse-leap:latest --FLAVOR=alpine-opensuse-leap
MEMORY=9048 \
KVM=true \
USE_QEMU=false \
CPUS=4 \
MACHINE_DISPLAY=true \
KEEP_VM=true \
CREATE_VM=true \
CONTAINER_IMAGE=ttl.sh/kairos-alpine-opensuse-leap-3b5156b9945a9180077d5c7c157265079c72b6e4:8h \
ISO=/home/xxx/Software/spectro-cloud/kairos/build/kairos-core-alpine-opensuse-leap.iso \
FLAVOR=alpine \
ginkgo run -v --label-filter upgrade-with-cli tests/
```

**Comment by jimmykarily** [comment]
This will probably change when we are done with the refactoring described here: https://github.com/kairos-io/kairos/issues/209#issuecomment-1464224461

Up to now, the kairos config tried to be both: a specific config for the kairos-agent and a generic config for every component (kcrypt, elemental-cli etc).

After the refactoring, any consumer that needs the full (generic) config, will use the new collector package and if needed will unmarshal that to a more "specific" struct.

Having said this, there is no need to block this PR since the refactoring is in progress and hasn't touched this file yet.

**Comment by oz123** [comment]
@jimmykarily you'll have to approve and merge since I can't do it.

**Review by mudler — APPROVED** [review]

**Pull request merged**
