### PR TITLE
:arrow_up: Update repositories

### PR DESCRIPTION
**Pull request by ci-robbot**
Bump of Kairos repositories

### CODE REVIEW

**Comment by Itxaka** [comment]
This brings immucore v0.17.0 which has support for LVM. Not sure if we want it to be a part of 2.0.1? @mudler

**Comment by mudler** [comment]
2.0.1 just tagged, this is unblocked, unless we plan another patch release

**Review by Itxaka — CHANGES_REQUESTED** [review]
fedora and rockylinux have no lvm module?

**Comment by Itxaka** [comment]
https://github.com/kairos-io/kairos/pull/1331 already bumps the repos

**Pull request closed without merging**
