### PR TITLE
Bump framework and osbuilder

### PR DESCRIPTION
**Pull request by Itxaka**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by Itxaka** [comment]
check is not working, @mauromorales was right :sob:

**Comment by Itxaka** [comment]
issues seems to be a different thing, `kairos-agent state get kairos.init` is not working as expected and that was introduced a few days ago and got lumped with this change. It should as soon as framework is rebuilt with the updated package

**Comment by Itxaka** [comment]
Most of the stuff seems to work now. Manual tested uki and also installs and triggers correctly. Will need to check the test.

upgrade job, no idea, need to manually test to see if there is any incompatibility between 2.5 and 3, but alpine one passes...

**Review by mauromorales — APPROVED** [review]

**Comment by Itxaka** [comment]
so the actual error for the upgrade is:

```
      +run-qemu-test |   [FAILED] sudo: you do not exist in the passwd database
```

which is baffling... 

This is installing a v2.5.0 image, and it fails during that install...so I have no idea why that would fail somehow????

**Comment by Itxaka** [comment]
current framework is main but I just cut 2.7.1, so if this pass with the current framework it will be ok to set the proper version and merge

**Pull request merged**
